issue #22 : fix examples
moead-framework/framework pull request #27
Opened 2021-03-23 09:26 UTC by geoffreyp

fix readme.md and example in the documentation

2021-03-29 09:08 UTC, sjvrijn requested changes

2021-03-29 09:08 UTC, sjvrijn commented on README.md
> +
Because of the indentation, the formatting is currently broken.
Easiest way to fix this might be to surround the code by ` ```python ``` ` tags

2021-03-29 14:20 UTC, chkoar commented on README.md
> +    instance_file = "moead_framework/test/data/instances/rmnk_0_2_100_1_0.dat"
@sjvrijn see #16 and #17

2021-03-29 14:31 UTC, sjvrijn commented on README.md
> +    instance_file = "moead_framework/test/data/instances/rmnk_0_2_100_1_0.dat"
@chkoar I agree that these issues still have to be sufficiently addressed, and the result of that should also be applied to update these examples. But I think that is separate from the main issue I'm pointing out in this line, which is that an example file should not explicitly include a relative path like this, as there is no guarantee that path can be successfully resolved wherever the user may decide to run their example. Especially when this package is `pip install`ed, this relative path will *always* fail

2021-03-31 08:28 UTC, geoffreyp commented
the full path of files is reverted and I fixed the code formatting in 22534e9  of this PR

2021-03-31 09:34 UTC, sjvrijn approved these changes

2021-03-31 10:07 UTC, merged