update the __repr__ method of the solution
moead-framework/framework pull request #49
Opened 2021-03-30 14:50 UTC by geoffreyp

new representation of solutions : 
Solution(F(x)=[..., ...., ....] ; x=[..,..,..,..,..,..])

2021-03-30 15:25 UTC, sjvrijn requested changes

2021-03-30 15:25 UTC, sjvrijn commented on moead_framework/solution/one_dimension_solution.py
> +        return "Solution(F(x)=" + str(self.F) + " ; x=" +str(list(self.solution)) + ")"
This does not conform to the specification for `__repr__` as stated in the [Python documentation](https://docs.python.org/3/reference/datamodel.html#object.__repr__).
For `__repr__` we would expect `f'OneDimensionSolution(solution={self.solution}, f={self.F})'`, which can be parsed by `eval()` and is intended for use by developers.

The `__str__` method is intended to provide a more user-friendly string representation, which can be the format you specify in this commit.

2021-03-31 07:52 UTC, geoffreyp commented on moead_framework/solution/one_dimension_solution.py
> +        return "Solution(F(x)=" + str(self.F) + " ; x=" +str(list(self.solution)) + ")"
I fixed it in the commit d099d4a in this PR

2021-03-31 07:55 UTC, sjvrijn requested changes

2021-03-31 07:55 UTC, sjvrijn commented on moead_framework/solution/one_dimension_solution.py
> +        return "Solution(F(x)=" + str(self.F) + " ; x=" +str(list(self.solution)) + ")"
My suggestion was using the f-string syntax of Python 3.6+: https://docs.python.org/3/tutorial/inputoutput.html#tut-f-strings

2021-03-31 07:55 UTC, sjvrijn commented on moead_framework/solution/one_dimension_solution.py
> +        return "f'OneDimensionSolution(solution={" + str(list(self.solution)) + "}, f={" + str(self.F) + "})'"
`return f'OneDimensionSolution(solution={list(self.solution)}, f={self.F})'`
This takes care of the formatting in Python 3.6+, without needing `str()` calls and manually joining substrings with `+`

2021-03-31 08:14 UTC, geoffreyp commented on moead_framework/solution/one_dimension_solution.py
> +        return "f'OneDimensionSolution(solution={" + str(list(self.solution)) + "}, f={" + str(self.F) + "})'"
I fixed it 3485349

2021-04-07 21:45 UTC, sjvrijn requested changes
Great, just one final request, then it's perfect

2021-04-07 21:45 UTC, sjvrijn commented on moead_framework/solution/one_dimension_solution.py
> +        return f'OneDimensionSolution(solution={self.solution}, f={self.F})'
One final request: wrap `self.solution` in a `list()` call, so `f'OneDimensionSolution(solution={list(self.solution)}, f={self.F})'`

An `eval(repr(x))` round-trip works fine without the `list()` call if `self.solution` is a list, but if it's a numpy array, this errors:

```python
>>> tmp = OneDimensionSolution([1,2,3], f=[2,3])
>>> eval(repr(tmp)).__dict__ == tmp.__dict__  # comparing on __dict__ for a quick equality check 
True
>>> tmp = OneDimensionSolution(np.array([1,2,3]), f=[2,3])
>>> eval(repr(tmp)).__dict__ == tmp.__dict__
Traceback (most recent call last):
    [...]
    OneDimensionSolution(solution=[1 2 3], f=[2, 3])
                         ^
SyntaxError: expression cannot contain assignment, perhaps you meant "=="?
```

The reason is that numpy arrays are by default displayed without commas between their elements. This is avoided with a `list()` call:
```python
>>> x = np.array([1, 2, 3])
>>> print(f'array x is {x}')
array x is [1 2 3]
             ^ ^
        # just spaces, no commas
>>> print(f'array x is {list(x)}')
array x is [1, 2, 3]
             ^  ^
       # now with commas
```

2021-04-09 08:22 UTC, geoffreyp commented on moead_framework/solution/one_dimension_solution.py
> +        return f'OneDimensionSolution(solution={self.solution}, f={self.F})'
it's done with 919c4b1

2021-04-13 21:10 UTC, sjvrijn approved these changes

2021-04-14 07:43 UTC, merged