update community guidelines
moead-framework/framework pull request #52
Opened 2021-03-31 10:04 UTC by geoffreyp

2021-04-07 21:19 UTC, sjvrijn requested changes
Looks good, that covers the issue and PR cases.
The only thing missing is where/how people can get help if they have any questions about the framework. Common options are providing an email address, chat room or suggesting users open an issue.

2021-04-07 21:19 UTC, sjvrijn commented on CONTRIBUTING.md
> +- all steps to reproduce the bug
It's a good idea to ask these kinds of things from people opening an issue.
Optional suggestion: you can use this list as an [issue template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository).

2021-04-09 08:14 UTC, geoffreyp commented
I added a section about GitHub Discussions in contributing.md (e979f6f) and 2 issue templates (4e3eedc)

2021-04-13 21:07 UTC, sjvrijn approved these changes

2021-04-14 07:42 UTC, merged