add tuto and example about results of algorithms
moead-framework/framework pull request #53
Opened 2021-03-31 12:55 UTC by geoffreyp

2021-04-07 21:26 UTC, sjvrijn requested changes
Great! Thanks for adding these examples.
All fine by me after the two spelling updates.

2021-04-07 21:26 UTC, sjvrijn commented on docs/tuto.rst
> +The method `run()` of each algorithm return a list of :class:`moead_framework.solution.one_dimension_solution.OneDimensionSolution`.
grammar: returns

2021-04-07 21:26 UTC, sjvrijn commented on docs/tuto.rst
> +    list_of_solution = moead.run(checkpoint=checkpt)
grammatically correct would be `list_of_solutions`, although just `solutions` would also be fine

2021-04-09 08:32 UTC, geoffreyp commented
Thank you, it's done in c39ca19

2021-04-13 21:05 UTC, sjvrijn approved these changes

2021-04-14 07:41 UTC, merged