update documentation with tools api
moead-framework/framework pull request #55
Opened 2021-03-31 14:13 UTC by geoffreyp

2021-05-27 15:28 UTC, sjvrijn commented on moead_framework/algorithm/combinatorial/moead_dra.py
> +        :param checkpoint: {function} The default value is None. The checkpoint can be used to save data during the process
This currently does not specify what arguments the function `checkpoint` should accept or how it should work. From this, it is not obvious that `checkpoint` should be defined with an external reference to the algorithm instance like in the [tutorials section](https://moead-framework.github.io/framework/html/tuto.html?highlight=checkpoint#save-data-with-the-framework) of the documentation.

Please refer to a `checkpoint` function specification or an example in these docstrings.

See also #64

2021-05-27 15:28 UTC, sjvrijn commented on moead_framework/problem/combinatorial/knapsack.py
> +    >>> instance_file = "moead_framework/test/data/instances/mubqp_0_2_25_0.8_0.dat"
Should a knapsack problem use an mubqp instance file?

2021-05-28 09:13 UTC, geoffreyp commented on moead_framework/problem/combinatorial/knapsack.py
> +    >>> instance_file = "moead_framework/test/data/instances/mubqp_0_2_25_0.8_0.dat"
Fixed with the commit 70ea112

2021-05-28 09:13 UTC, geoffreyp commented on moead_framework/algorithm/combinatorial/moead_dra.py
> +        :param checkpoint: {function} The default value is None. The checkpoint can be used to save data during the process
Documentation updated with the commit 4717ec3

2021-05-28 09:42 UTC, sjvrijn requested changes

2021-05-28 09:42 UTC, sjvrijn commented on docs/tuto.rst
>      moead.run(checkpoint=checkpt)
`checkpoint=checkpt` should also be updated here

2021-06-01 12:32 UTC, sjvrijn requested changes

2021-06-01 12:32 UTC, sjvrijn commented on docs/tools.rst
> +
`moead_framework.tool.result.checkpoint` should be added. Have you considered using the [`:members:` directive](https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html#directive-option-automodule-members) instead of having to manually add every function?

2021-06-02 14:46 UTC, geoffreyp commented on docs/tools.rst
> +
Added in the commit c3fce1e

2021-06-02 14:46 UTC, geoffreyp commented on docs/tuto.rst
> +    moead.run(checkpoint=checkpoint)
fixed in the commit c3fce1e

2021-06-02 14:46 UTC, geoffreyp commented on docs/tuto.rst
> +    def checkpoint(moead_algorithm: AbstractMoead)::
fixed in the commit c3fce1e

2021-07-19 14:31 UTC, sjvrijn approved these changes
Just hereby noting my approval of these changes while waiting for @chkoar

2021-07-19 15:54 UTC, chkoar commented
> Just hereby noting my approval of these changes while waiting for @chkoar

To many change to be reviewed one by one but it is definitely an improvement. I suppose it can safely be merged.

2021-07-20 09:02 UTC, merged