add more informations about compatibility between each components
moead-framework/framework pull request #66
Opened 2021-05-28 11:15 UTC by geoffreyp

2021-06-01 14:27 UTC, sjvrijn requested changes

2021-06-01 14:27 UTC, sjvrijn commented on moead_framework/core/selector/delta_selector.py
> +        except Exception:
I think you can simplify the 
```python
try:
    if not hasattr(...):
        raise
except Exception:
    raise ValueError(msg)
```
blocks to the more concise
```python
if not hasattr(...):
    raise ValueError(msg)
```

2021-06-01 14:27 UTC, sjvrijn commented on moead_framework/core/selector/delta_selector.py
> +            msg = "The algorithm does not seem to be compatible with the component DeltaSelector. The parameter delta is required in the algorithm by the component DeltaSelector."
Error messages should be short and to the point.
Would summarize this one to: "Algorithm lacks required parameter 'delta' for component 'DeltaSelector'. "

2021-06-01 14:27 UTC, sjvrijn commented on moead_framework/core/selector/delta_selector.py
> +            raise ValueError(msg)
`AttributeError` seems like the better error here

2021-06-01 14:27 UTC, sjvrijn commented on moead_framework/core/sps_strategy/sps_dra.py
> +            msg = "The algorithm does not seem to be compatible with the component SpsDra. The attribute pi is required in the algorithm to stock all utility values of each sub-problems."
"Algorithm lacks required parameter 'pi' for component 'SpsDra'."

2021-06-01 14:27 UTC, sjvrijn commented on moead_framework/core/sps_strategy/sps_dra.py
> +            raise ValueError(msg)
`AttributeError`

2021-06-01 14:27 UTC, sjvrijn commented on moead_framework/core/sps_strategy/sps_random_and_boundaries.py
> +            msg = "The algorithm does not seem to be compatible with the component SpsRandomAndBoundaries. The attribute number_of_subproblem is required in the algorithm to define the number of sub-
Algorithm lacks required parameter 'number_of_subproblem' for component 'SpsRandomAndBoundaries'.

2021-06-01 14:27 UTC, sjvrijn commented on moead_framework/core/sps_strategy/sps_random_and_boundaries.py
> +            raise ValueError(msg)
`AttributeError`

2021-06-01 14:27 UTC, sjvrijn commented on moead_framework/core/genetic_operator/abstract_operator.py
> +            msg = "The algorithm does not seem to be compatible with the current genetic operator. The current genetic oeperator needs {n} solutions as parents and it received {badn} solution(s)."
"Selected genetic operator needs {n} solutions as parents, but received {badn} solution(s)"

Could be further specified using `self.__class__.__name__` if you'd want
```python
f"{self.__class__.__name__} needs {n} solutions as parents, but received {len(self.solutions)} solution(s)"
```

2021-06-02 13:11 UTC, geoffreyp commented on moead_framework/core/genetic_operator/abstract_operator.py
> +            msg = "The algorithm does not seem to be compatible with the current genetic operator. The current genetic oeperator needs {n} solutions as parents and it received {badn} solution(s)."
Fixed in 233c694

2021-06-02 13:11 UTC, geoffreyp commented on moead_framework/core/sps_strategy/sps_random_and_boundaries.py
> +            raise ValueError(msg)
Fixed in 233c694

2021-06-02 13:11 UTC, geoffreyp commented on moead_framework/core/sps_strategy/sps_random_and_boundaries.py
> +            msg = "The algorithm does not seem to be compatible with the component SpsRandomAndBoundaries. The attribute number_of_subproblem is required in the algorithm to define the number of sub-
Fixed in 233c694

2021-06-02 13:11 UTC, geoffreyp commented on moead_framework/core/sps_strategy/sps_dra.py
> +            raise ValueError(msg)
Fixed in 233c694

2021-06-02 13:11 UTC, geoffreyp commented on moead_framework/core/sps_strategy/sps_dra.py
> +            msg = "The algorithm does not seem to be compatible with the component SpsDra. The attribute pi is required in the algorithm to stock all utility values of each sub-problems."
Fixed in 233c694

2021-06-02 13:11 UTC, geoffreyp commented on moead_framework/core/selector/delta_selector.py
> +            raise ValueError(msg)
Fixed in 233c694

2021-06-02 13:11 UTC, geoffreyp commented on moead_framework/core/selector/delta_selector.py
> +            msg = "The algorithm does not seem to be compatible with the component DeltaSelector. The parameter delta is required in the algorithm by the component DeltaSelector."
Fixed in 233c694

2021-06-02 13:11 UTC, geoffreyp commented on moead_framework/core/selector/delta_selector.py
> +        except Exception:
Fixed in 233c694

2021-06-03 12:07 UTC, sjvrijn approved these changes
Looks good to me :+1:

2021-06-04 07:41 UTC, merged